spring:
  application:
    name: redis-demo
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}